server:
  port: 8085
#设置日志级别会给root根节点设置，代表整体应用的级别
logging:
  level:
    root: info
spring:
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    #发件人
    username: abc@qq.com
    #授权码
    password: hmps234234
    port: 465
    properties:
      mail:
        debug: true
        smtp:
          ssl:
            enable: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ilds?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    #    password: 787186571
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
